#!/usr/bin/env python3
"""Generate HTCondor submit and DAG files for parallel coatopt runs.

Usage:
    python generate_condor_dag.py --config ppo_seq.ini

Your experiment config file should include a [condor] section:
    [condor]
    materials_file = materials.json
    num_runs = 10
    project_path = /path/to/coatopt_simple
    results_dir = runs/  # directory to transfer back (where results are saved)
    uv_executable = /usr/bin/uv
    output_dir = condor_runs  # optional, defaults to condor_runs

    # Resource requirements (optional)
    request_cpus = 1
    request_memory = 4GB
    request_disk = 1GB
"""

import argparse
import configparser
from pathlib import Path


def generate_submit_file(
    config: configparser.ConfigParser, config_file_path: str, output_dir: Path
) -> Path:
    """Generate HTCondor submit file with variable substitution."""

    # Get config values
    materials_file = config.get("condor", "materials_file")
    project_path = config.get("condor", "project_path")
    results_dir = config.get("condor", "results_dir", fallback="runs/")
    uv_executable = config.get("condor", "uv_executable", fallback="/usr/bin/uv")

    # Resource requirements
    request_cpus = config.get("condor", "request_cpus", fallback="1")
    request_memory = config.get("condor", "request_memory", fallback="4GB")
    request_disk = config.get("condor", "request_disk", fallback="1GB")

    submit_content = f"""# HTCondor submit file for parallel coatopt experiments
# Generated by generate_condor_dag.py

# Universe and executable
universe = vanilla
executable = {uv_executable}

# Arguments - run_id will be set by DAG
arguments = --project {project_path} run python -m coatopt.run --config {config_file_path} --run-name $(run_id)

# Output files - $(run_id) is substituted by DAG
output = logs/job_$(run_id).out
error = logs/job_$(run_id).err
log = logs/job_$(run_id).log

# Resource requirements
request_cpus = {request_cpus}
request_memory = {request_memory}
request_disk = {request_disk}

# Transfer config and materials files
should_transfer_files = YES
transfer_input_files = {config_file_path}, {materials_file}
transfer_output_files = {results_dir}
when_to_transfer_output = ON_EXIT

# Queue - will be controlled by DAG
queue 1
"""

    submit_file = output_dir / "coatopt.submit"
    submit_file.write_text(submit_content)
    print(f"Generated submit file: {submit_file}")
    return submit_file


def generate_dag_file(
    config: configparser.ConfigParser, output_dir: Path, submit_file: Path
) -> Path:
    """Generate HTCondor DAG file for parallel runs."""

    num_runs = config.getint("condor", "num_runs")

    dag_content = f"""# HTCondor DAG file for parallel coatopt experiments
# Generated by generate_condor_dag.py
# This will run {num_runs} parallel experiments

"""

    # Generate job entries
    for run_id in range(1, num_runs + 1):
        dag_content += f"""JOB run_{run_id} {submit_file.name}
VARS run_{run_id} run_id="run{run_id:03d}"

"""

    dag_file = output_dir / "coatopt.dag"
    dag_file.write_text(dag_content)
    print(f"Generated DAG file: {dag_file}")
    return dag_file


def main():
    parser = argparse.ArgumentParser(
        description="Generate HTCondor submit and DAG files for parallel coatopt runs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config",
        type=str,
        help="Path to DAG configuration file (dag_config.ini)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for generated files (overrides config)",
    )

    args = parser.parse_args()

    # Read config
    config = configparser.ConfigParser()
    config.read(args.config)

    # Get or create output directory
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        output_dir = Path(config.get("condor", "output_dir", fallback="condor_runs"))

    output_dir.mkdir(parents=True, exist_ok=True)

    # Create logs directory
    logs_dir = output_dir / "logs"
    logs_dir.mkdir(exist_ok=True)

    # Generate files
    submit_file = generate_submit_file(config, args.config, output_dir)
    dag_file = generate_dag_file(config, output_dir, submit_file)

    print(f"\n✓ Files generated successfully in {output_dir}/")
    print(f"\nTo submit the DAG:")
    print(f"  cd {output_dir}")
    print(f"  condor_submit_dag {dag_file.name}")
    print(f"\nTo monitor progress:")
    print(f"  condor_q")
    print(f"  tail -f {dag_file.stem}.dagman.out")


if __name__ == "__main__":
    main()
