#!/usr/bin/env python3
"""Generate HTCondor submit and DAG files for parallel coatopt runs.

Usage:
    python generate_condor_dag.py --config ppo_seq.ini

Your experiment config file should include a [condor] section:
    [condor]
    materials_file = materials.json
    num_runs = 10
    project_path = /path/to/coatopt_simple  # Must have .venv/ with coatopt installed
    results_dir = runs/  # directory to transfer back (where results are saved)
    output_dir = condor_runs  # optional, defaults to condor_runs

    # Resource requirements (optional)
    request_cpus = 1
    request_memory = 4GB
    request_disk = 1GB
"""

import argparse
import configparser
from pathlib import Path


def generate_submit_file(
    config: configparser.ConfigParser,
    config_file_path: str,
    materials_file_path: str,
    output_dir: Path,
) -> Path:
    """Generate HTCondor submit file with variable substitution."""

    # Get config values
    project_path = config.get("condor", "project_path")
    results_dir = config.get("condor", "results_dir", fallback="runs/")
    venv_path = f"{project_path}/.venv"

    # Get base run name to append run_id to
    base_run_name = config.get("general", "run_name", fallback="")

    # Convert to absolute paths for transfer_input_files
    config_absolute = Path(config_file_path).resolve()

    # Check if comparison should be generated
    generate_comparison = config.getboolean(
        "condor", "generate_comparison", fallback=False
    )
    comparison_flag = " --generate-comparison" if generate_comparison else ""

    # Resource requirements
    request_cpus = config.get("condor", "request_cpus", fallback="1")
    request_memory = config.get("condor", "request_memory", fallback="4GB")
    request_disk = config.get("condor", "request_disk", fallback="1GB")

    # Check if results_dir is absolute path (for output transfer only)
    transfer_outputs = not Path(results_dir).is_absolute()

    submit_content = f"""# HTCondor submit file for parallel coatopt experiments
# Generated by generate_condor_dag.py

# Universe and executable (use absolute path from shared filesystem)
universe = vanilla
executable = {venv_path}/bin/python

# Arguments - run_id and seed will be set by DAG
# Use absolute paths since we're on shared filesystem
arguments = -m coatopt.run --config {config_absolute} --run-name {base_run_name}_$(run_id) --seed $(seed){comparison_flag}

# Output files - $(run_id) is substituted by DAG
output = logs/job_$(run_id).out
error = logs/job_$(run_id).err
log = logs/job_$(run_id).log

# Resource requirements
request_cpus = {request_cpus}
request_memory = {request_memory}
request_disk = {request_disk}

# File transfer - use shared filesystem (no transfer needed)
should_transfer_files = IF_NEEDED
{'transfer_output_files = ' + results_dir if transfer_outputs else '# Results written directly to ' + results_dir}
{'when_to_transfer_output = ON_EXIT' if transfer_outputs else ''}

# Queue - will be controlled by DAG
queue 1
"""

    submit_file = output_dir / "coatopt.submit"
    submit_file.write_text(submit_content)
    print(f"Generated submit file: {submit_file}")
    return submit_file


def generate_dag_file(
    config: configparser.ConfigParser, output_dir: Path, submit_file: Path
) -> Path:
    """Generate HTCondor DAG file for parallel runs."""

    num_runs = config.getint("condor", "num_runs")
    base_seed = config.getint("condor", "base_seed", fallback=1000)

    dag_content = f"""# HTCondor DAG file for parallel coatopt experiments
# Generated by generate_condor_dag.py
# This will run {num_runs} parallel experiments

"""

    # Generate job entries with unique seeds
    for run_id in range(1, num_runs + 1):
        seed = base_seed + run_id
        dag_content += f"""JOB run_{run_id} {submit_file.name}
VARS run_{run_id} run_id="run{run_id:03d}" seed="{seed}"

"""

    dag_file = output_dir / "coatopt.dag"
    dag_file.write_text(dag_content)
    print(f"Generated DAG file: {dag_file}")
    return dag_file


def main():
    parser = argparse.ArgumentParser(
        description="Generate HTCondor submit and DAG files for parallel coatopt runs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config",
        type=str,
        help="Path to DAG configuration file (dag_config.ini)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for generated files (overrides config)",
    )

    args = parser.parse_args()

    # Read config
    config = configparser.ConfigParser()
    config.read(args.config)

    # Get or create output directory
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        output_dir = Path(config.get("condor", "output_dir", fallback="condor_runs"))

    # Check if output directory already exists
    if output_dir.exists():
        print(f"\nWARNING: Output directory already exists: {output_dir}")
        print("This may overwrite existing submit/DAG files.")
        response = input("Continue? [y/N]: ")
        if response.lower() != "y":
            print("Aborted.")
            return

    output_dir.mkdir(parents=True, exist_ok=True)

    # Create logs directory
    logs_dir = output_dir / "logs"
    logs_dir.mkdir(exist_ok=True)

    # Copy config and materials files to output directory to freeze them for this DAG
    import shutil

    config_source = Path(args.config).resolve()
    config_copy = output_dir / config_source.name
    shutil.copy(config_source, config_copy)
    print(f"Copied config to: {config_copy}")

    materials_file = config.get("condor", "materials_file")
    materials_source = Path(materials_file).resolve()
    materials_copy = output_dir / materials_source.name
    shutil.copy(materials_source, materials_copy)
    print(f"Copied materials to: {materials_copy}")

    # Generate files
    submit_file = generate_submit_file(
        config, str(config_copy), str(materials_copy), output_dir
    )
    dag_file = generate_dag_file(config, output_dir, submit_file)

    print(f"\n✓ Files generated successfully in {output_dir}/")
    print("\nTo submit the DAG:")
    print(f"  cd {output_dir}")
    print(f"  condor_submit_dag {dag_file.name}")
    print("\nTo monitor progress:")
    print("  condor_q")
    print(f"  tail -f {dag_file.stem}.dagman.out")


if __name__ == "__main__":
    main()
